name: FantasticBits
channels:
  - pytorch
  - conda-forge
dependencies:
  - black
  - cudatoolkit=11.3
  - isort
  - matplotlib
  - numpy
  - pandas
  - pytest
  - python=3.9
  - pytorch
  - scipy
  - seaborn
  - snakeviz
  - tensorboard
  - tqdm
  - pip
  - pip:
      - ray[tune]
      - pygame